#
# Stack configuration for the Shibboleth IdP.
#

version: "3.5"

services:

  idp:
    image: ${IMAGE_NAME}
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          # Constrain to uf01 because that's where
          # the host volumes we need to mount are.
          - "node.hostname == uf01"
          # The custom image is only built for a single architecture
          - "node.platform.arch == x86_64"
      labels:
        # Enable the service
        - "traefik.enable=true"
        - "traefik.http.services.idp.loadbalancer.server.port=80"
        # https://idp2.iay.org.uk/
        - "traefik.http.routers.idp.entrypoints=websecure"
        - "traefik.http.routers.idp.tls=true"
        - "traefik.http.routers.idp.tls.certResolver=le"
        - "traefik.http.routers.idp.rule=Host(`idp2.iay.org.uk`)"
        - "traefik.http.routers.idp.service=idp"
    volumes:
      - type: bind
        source: ./shibboleth-idp
        target: /opt/shibboleth-idp
      - type: bind
        source: ./logs/jetty
        target: /opt/jetty-base/logs

networks:
  default:
    external: true
    name: traefik
