name: Build and Push IdP KWU AC KR

on:
  push:
    branches:
      - idp-kwu-ac-kr
  pull_request:
    branches:
      - idp-kwu-ac-kr

env:
  REGISTRY: registry.bitgaram.info
  IMAGE_NAME: idp-kwu-ac-kr

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: 'admin' 
        password: 'qlcrkfka1#'

    - name: Load environment variables
      shell: bash
      run: |
        # Load VERSIONS file
        source ./VERSIONS
        echo "JAVA_VERSION=$JAVA_VERSION" >> $GITHUB_ENV
        echo "JETTY_BASE_VERSION=$JETTY_BASE_VERSION" >> $GITHUB_ENV
        
        # Generate timestamp
        TIMESTAMP=$(date +"%Y%m%d%H%M%S")
        echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV
        
        # Set image tags
        echo "IMAGE_TAG_TIMESTAMP=${REGISTRY}/${IMAGE_NAME}:$TIMESTAMP" >> $GITHUB_ENV
        echo "IMAGE_TAG_LATEST=${REGISTRY}/${IMAGE_NAME}:latest" >> $GITHUB_ENV

    - name: Fetch Jetty and Shibboleth components
      run: |
        echo "Fetching Jetty distribution..."
        chmod +x ./fetch-jetty
        ./fetch-jetty
        
        echo "Fetching Shibboleth IdP distribution..."
        chmod +x ./fetch-shib
        ./fetch-shib
    
    - name: Build and prepare components
      run: |
        echo "Running build script to prepare overlay and components..."
        chmod +x ./build
        ./build
    
    - name: Debug build arguments and environment
      shell: bash
      run: |
        echo "=== Environment Variables Before Build ==="
        echo "REGISTRY: ${REGISTRY}"
        echo "IMAGE_NAME: ${IMAGE_NAME}"
        echo "JAVA_VERSION: ${JAVA_VERSION}"
        echo "JETTY_BASE_VERSION: ${JETTY_BASE_VERSION}"
        echo "IMAGE_TAG_TIMESTAMP: ${IMAGE_TAG_TIMESTAMP}"
        echo "IMAGE_TAG_LATEST: ${IMAGE_TAG_LATEST}"
        echo "========================="
        echo "=== Build Arguments to be passed ==="
        echo "JAVA_VERSION: ${JAVA_VERSION}"
        echo "JETTY_BASE_VERSION: ${JETTY_BASE_VERSION}"
        echo "IDP_SCOPE: kwu.ac.kr"
        echo "IDP_SCOPE_DOMAIN: kwu.ac.kr"
        echo "IDP_HOST_NAME: idp.kwu.ac.kr"
        echo "IDP_ENTITYID: https://idp.kwu.ac.kr/idp/shibboleth"
        echo "IDP_ORG_DISPLAYNAME: Kwangwoon University"
        echo "IDP_ORG_HOMEPAGE: https://www.kw.ac.kr"
        echo "========================="
    
    - name: Build Docker image with direct docker command
      shell: bash
      run: |
        echo "Building Docker image with direct docker build command..."
        echo "=== Full Docker Build Command ==="
        echo "docker build \\"
        echo "  --no-cache \\"
        echo "  --build-arg \"JAVA_VERSION=${JAVA_VERSION}\" \\"
        echo "  --build-arg \"JETTY_BASE_VERSION=${JETTY_BASE_VERSION}\" \\"
        echo "  --build-arg \"IDP_SCOPE=kwu.ac.kr\" \\"
        echo "  --build-arg \"IDP_SCOPE_DOMAIN=kwu.ac.kr\" \\"
        echo "  --build-arg \"IDP_HOST_NAME=idp.kwu.ac.kr\" \\"
        echo "  --build-arg \"IDP_ENTITYID=https://idp.kwu.ac.kr/idp/shibboleth\" \\"
        echo "  --build-arg \"IDP_ORG_DISPLAYNAME=Kwangwoon University\" \\"
        echo "  --build-arg \"IDP_ORG_HOMEPAGE=https://www.kw.ac.kr\" \\"
        echo "  -t \"${IMAGE_TAG_TIMESTAMP}\" \\"
        echo "  -t \"${IMAGE_TAG_LATEST}\" ."
        echo "========================="
        
        docker build \
          --no-cache \
          --build-arg "JAVA_VERSION=${JAVA_VERSION}" \
          --build-arg "JETTY_BASE_VERSION=${JETTY_BASE_VERSION}" \
          --build-arg "IDP_SCOPE=kwu.ac.kr" \
          --build-arg "IDP_SCOPE_DOMAIN=kwu.ac.kr" \
          --build-arg "IDP_HOST_NAME=idp.kwu.ac.kr" \
          --build-arg "IDP_ENTITYID=https://idp.kwu.ac.kr/idp/shibboleth" \
          --build-arg "IDP_ORG_DISPLAYNAME=Kwangwoon University" \
          --build-arg "IDP_ORG_HOMEPAGE=https://www.kw.ac.kr" \
          -t "${IMAGE_TAG_TIMESTAMP}" \
          -t "${IMAGE_TAG_LATEST}" .
    
    - name: Push Docker images
      shell: bash
      run: |
        echo "Pushing images to registry..."
        docker push "${IMAGE_TAG_TIMESTAMP}"
        docker push "${IMAGE_TAG_LATEST}"
        
        echo "Successfully pushed:"
        echo "  - ${IMAGE_TAG_TIMESTAMP}"
        echo "  - ${IMAGE_TAG_LATEST}"
    
    - name: Image scan (optional)
      continue-on-error: true
      shell: bash
      run: |
        echo "Image built and pushed successfully!"
        echo "Image: ${IMAGE_TAG_TIMESTAMP}"
        echo "Latest: ${IMAGE_TAG_LATEST}"
