name: Build and Push IdP KWU AC KR

on:
  push:
    branches:
      - idp-kwu-ac-kr
  pull_request:
    branches:
      - idp-kwu-ac-kr

env:
  REGISTRY: registry.bitgaram.info
  IMAGE_NAME: idp-kwu-ac-kr

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: 'admin' 
        password: 'qlcrkfka1#'

    - name: Load environment variables
      run: |
        # Load VERSIONS file
        source ./VERSIONS
        echo "JAVA_VERSION=$JAVA_VERSION" >> $GITHUB_ENV
        echo "JETTY_BASE_VERSION=$JETTY_BASE_VERSION" >> $GITHUB_ENV
        
        # Generate timestamp
        TIMESTAMP=$(date +"%Y%m%d%H%M%S")
        echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV
        
        # Set image tags
        echo "IMAGE_TAG_TIMESTAMP=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$TIMESTAMP" >> $GITHUB_ENV
        echo "IMAGE_TAG_LATEST=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest" >> $GITHUB_ENV

    - name: Fetch Jetty and Shibboleth components
      run: |
        echo "Fetching Jetty distribution..."
        chmod +x ./fetch-jetty
        ./fetch-jetty
        
        echo "Fetching Shibboleth IdP distribution..."
        chmod +x ./fetch-shib
        ./fetch-shib
    
    - name: Build and prepare components
      run: |
        echo "Running build script to prepare overlay and components..."
        chmod +x ./build
        ./build
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ env.IMAGE_TAG_TIMESTAMP }}
          ${{ env.IMAGE_TAG_LATEST }}
        build-args: |
          JAVA_VERSION=${{ env.JAVA_VERSION }}
          JETTY_BASE_VERSION=${{ env.JETTY_BASE_VERSION }}
          IDP_SCOPE=kwu.ac.kr
          IDP_SCOPE_DOMAIN=kwu.ac.kr
          IDP_HOST_NAME=idp.kwu.ac.kr
          IDP_ENTITYID=https://idp.kwu.ac.kr/idp/shibboleth
          IDP_ORG_DISPLAYNAME=Kwangwoon University
          IDP_ORG_HOMEPAGE=https://www.kw.ac.kr
          IDP_FORGOT_PASSWORD_URL=
          IDP_SUPPORT_URL=
    
    - name: Image scan (optional)
      continue-on-error: true
      run: |
        echo "Image built and pushed successfully!"
        echo "Image: ${{ env.IMAGE_TAG_TIMESTAMP }}"
        echo "Latest: ${{ env.IMAGE_TAG_LATEST }}"
